{{- if .Values.qsvcAutoCleanup.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-qsvc-deleter-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [ "gigaspaces.com" ]
    resources: [ "queryservices" ]
    verbs: [ "get", "list", "delete","patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-qsvc-deleter-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-qsvc-deleter-role
subjects:
  - kind: Group
    name: "system:serviceaccounts:{{ .Release.Namespace }}"
    namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-qsvc-deleter-sa
  namespace: {{ .Release.Namespace }}
---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-qsvc-deleter-job
  namespace:  {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-delete"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: pre-delete-qsvc-job
          image: "harbor.hq.bbwcorp.com/bbw_omni_channel_it/giga/bitnami/kubectl"
          command: [ "kubectl" ]
          args:
            - "delete"
            - "qsvc"
            - "--all"
            - "--wait=false"
      serviceAccountName: {{ .Release.Name }}-qsvc-deleter-sa
      securityContext:
        runAsUser: 0
{{- end }}
